server {
  listen 80;
  server_name bridgespero.com;

  location / {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  
    proxy_pass http://brsp-next:3000;
  }

  location ~ ^/(api/v1|swagger-ui|v3/api-docs|public) {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://brsp-spring:8080;
  }
}

server {
  listen 80;
  server_name ~^(dev|prod|meet)\.bridgespero\.com$;

  location / {
    deny all;
  }
}
