---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMaps.next }}
  labels:
    app.kubernetes.io/name: {{ template "brsp.name" . }}
    app.kubernetes.io/component: next
    helm.sh/chart: {{ template "brsp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    tier: frontend
data:
  {{- with (.Values.next).env }}
{{ toYaml . | indent 2 }}
  {{- end }}
