apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: next-bluegreen
  labels:
    app.kubernetes.io/name: {{ template "brsp.name" . }}
    app.kubernetes.io/component: frontend
    helm.sh/chart: {{ template "brsp.chart" . }}
    environment: bluegreen
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    tier: frontend
spec:
  replicas: {{ .Values.next.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "brsp.name" . }}
      app.kubernetes.io/component: next
      environment: bluegreen
      release: {{ $.Release.Name }}
      tier: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "brsp.name" . }}
        app.kubernetes.io/environment: bluegreen
        app.kubernetes.io/component: next
        environment: bluegreen
        release: {{ .Release.Name }}
        tier: frontend
    spec:
      containers:
        - name: next
          image: "{{ .Values.next.image.repository }}:{{ .Values.next.image.tag.bluegreen }}"
          imagePullPolicy: {{ .Values.next.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.next.containerPort }}
              protocol: TCP
          resources:
  {{- with $.Values.next }}
{{ toYaml .resources | indent 12 }}
    {{- with .nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
  {{- end }}
      imagePullSecrets:
        - name: {{ .Values.secrets.cr }}
  strategy:
    blueGreen: 
      # activeService specifies the service to update with the new template hash at time of promotion.
      # This field is mandatory for the blueGreen update strategy.
      activeService: next-bluegreen-active
      # previewService specifies the service to update with the new template hash before promotion.
      # This allows the preview stack to be reachable without serving production traffic.
      # This field is optional.
      previewService: next-bluegreen-preview
      # autoPromotionEnabled disables automated promotion of the new stack by pausing the rollout
      # immediately before the promotion. If omitted, the default behavior is to promote the new
      # stack as soon as the ReplicaSet are completely ready/available.
      # Rollouts can be resumed using: `kubectl argo rollouts promote ROLLOUT`
      autoPromotionEnabled: false
