---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "redis.service.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "brsp.name" . }}
    app.kubernetes.io/component: redis
    helm.sh/chart: {{ template "brsp.chart" . }}
    environment: bluegreen
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    tier: data
spec:
  type: ClusterIP
  ports:
    - name: tcp-redis
      port: {{ template "redis.port" . }}
      targetPort: {{ template "redis.port" . }}
    - name: tcp-sentinel
      port: {{ template "redis.sentinelPort" . }}
      targetPort: {{ template "redis.sentinelPort" . }}
  selector:
    app.kubernetes.io/name: {{ template "brsp.name" . }}
    app.kubernetes.io/component: redis
    helm.sh/chart: {{ template "brsp.chart" . }}
    environment: bluegreen
    release: {{ .Release.Name }}
    tier: data
