---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMaps.spring }}
  labels:
    app.kubernetes.io/name: {{ template "brsp.name" . }}
    app.kubernetes.io/component: spring
    helm.sh/chart: {{ template "brsp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    tier: backend
data:
  datasourceUrl: jdbc:postgresql://{{ template "postgres.service.name" }}-${BRSP_ENV}-rw.default.svc.cluster.local:5432/{{ .Values.postgres.initdb.database }}
  datasourceUsername: {{ .Values.postgres.initdb.owner }}
  replicaDatasourceUrl: jdbc:postgresql://{{ template "postgres.service.name" }}-${BRSP_ENV}-ro.default.svc.cluster.local:5432/{{ .Values.postgres.initdb.database }}
  redisHost: {{ template "redis.service.name" . }}-${BRSP_ENV}.default.svc.cluster.local
  zoomRedirectUri: ${BRSP_URL}/api/v1/zoom/oauth/callback
