{{ if (.Values.letsencrypt).enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "letsencrypt.issuerName" . }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: {{ template "letsencrypt.issuerName" . }}
    solvers:
    - http01:
        ingress:
          class: nginx
{{ end }}