{{ if (.Values.letsencrypt).enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "letsencrypt.issuerName" . }}
spec:
  acme:
    server: {{ .Values.letsencrypt.server }}
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: {{ template "letsencrypt.issuerName" . }}
    solvers:
    - http01:
        ingress:
          class: traefik
{{ end }}