---
apiVersion: v1
kind: Secret
metadata:
  name: db-user-secret
  labels:
    app.kubernetes.io/name: {{ template "brsp.name" . }}
    app.kubernetes.io/component: spring
    helm.sh/chart: {{ template "brsp.chart" . }}
    tier: backend
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.postgres.initdb.owner | b64enc }}
  password: {{ .Values.postgres.initdb.password | b64enc }}
